import logging
import httpx
import json
from mcp.server.fastmcp import FastMCP, Context
from utils.Utils import *

def register_printer_tools(mcp_server: FastMCP, wasdi_api_url: str):
    """Registers all tools related to configuring, storing, and generating map images or PDF print layouts."""

    @mcp_server.tool(name="printer_store_new_map")
    async def printer_store_new_map(oPrinterViewModel: dict, oContext: Context = None) -> str:
        """Stores a map layout configuration state on the server to generate an export image or document.
        
        Use this tool as the first step to freeze a map perspective before downloading or rendering 
        the final image or PDF payload.
        
        Args:
            oPrinterViewModel: A structured dictionary mapping the PrinterViewModel setup contract. 
                               Must include properties: 'baseMap', 'center' (lat/lng parameters map), 
                               and output 'format' ('pdf' or 'png').
        Returns:
            A unique tracking UUID string required by 'printer_print' to generate the actual file asset.
        """
        sSessionToken = getSessionToken(oContext)
        if not sSessionToken:
            raise ValueError("Missing x-session-token header")
        if not oPrinterViewModel:
            raise ValueError("Missing printer layout configuration view model.")

        # Safely convert the native dict into a clean JSON string for the backend payload content
        sPrinterViewModelJson = json.dumps(oPrinterViewModel)

        async with httpx.AsyncClient() as oClient:
            oResponse = await oClient.post(
                f"{wasdi_api_url}/rest/print/storemap",
                content=sPrinterViewModelJson,
                headers={
                    "x-session-token": sSessionToken,
                    "Content-Type": "application/json",
                },
            )
            oResponse.raise_for_status()
            logging.debug("WASDI printer_store_new_map completed successfully.")
            return oResponse.text


    @mcp_server.tool(name="printer_print")
    async def printer_print(sUUID: str, oContext: Context = None) -> str:
        """Generates and retrieves the final map image snapshot (PNG) or PDF document generated by a stored UUID layout.
        
        Use this tool following a successful execution of 'printer_store_new_map' to fetch the actual visual map layers.
        
        Args:
            sUUID: The tracking unique tracking identifier string returned by the layout storage tool.
        """
        sSessionToken = getSessionToken(oContext)
        if not sSessionToken:
            raise ValueError("Missing x-session-token header")
        if not sUUID:
            raise ValueError("Missing look-up validation UUID parameter.")

        async with httpx.AsyncClient() as oClient:
            oResponse = await oClient.get(
                f"{wasdi_api_url}/rest/print",
                params={"uuid": sUUID},
                headers={"x-session-token": sSessionToken},
            )
            oResponse.raise_for_status()
            logging.debug("WASDI printer_print execution completed successfully.")
            return oResponse.text